version: '3'

services:
  nginx:
      image: nginx:1.21.0
      container_name: nginx
      volumes:
          - ./:/var/www
          - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 80:80
      networks:
          - my-network
      depends_on:
          - server

  server:
    build:
        context: ./server
        dockerfile: ./Dockerfile.prod
    container_name: server
    volumes:
        - ./server:/var/www/server
    networks:
        my-network:
            aliases:
                - server
    ports:
        - 3000:3000
    env_file:
      - ".env.prod"

networks:
    my-network:
