version: '3.8'

services:
  mysql_db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    command:
      - --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: MGS_DATABASES
    ports:
      - "3309:3306"
    expose:
      - 3309
    volumes:
      - ../mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../mysql/initdb.d/create_table.sql:/docker-entrypoint-initdb.d/1.sql
      - ../mysql/initdb.d/insert_data.sql:/docker-entrypoint-initdb.d/2.sql

  nginx:
      image: nginx:1.21.0
      container_name: nginx
      volumes:
          - ../:/var/www
          - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 80:80
      networks:
          - my-network
      depends_on:
        - server

  server:
    build:
      context: ../server
      dockerfile: Dockerfile.dev
    command: npm run start
    volumes:
        - ../server:/var/www/server
    networks:
        my-network:
            aliases:
                - server
    expose:
        - 3000
    ports:
        - "3000:3000"
    env_file:
      - ".env.dev"
    depends_on:
      - mysql_db
    links:
      - mysql_db

networks:
    my-network: