FROM node:16-alpine

#Docker가 이 경로를 모든 후속 명령의 기본 위치로 설정하도록 함
WORKDIR /app

# package.json및 package-lock.json파일을 작업 디렉토리에 복사합니다 /app.
COPY package*.json ./

# ec2 배포 시, 힙 최대 사용 메모리 설정
ENV NODE_OPTIONS=--max_old_space_size=2048

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]